default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kci_development

test:
  <<: *default
  database: kci_test

production:
  <<: *default
  database: kci_production
  username: kci
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
